# Generated by Django 5.0.6 on 2024-07-12 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_trackinghistory_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestLogs',
        ),
    ]
