# Generated by Django 5.0.6 on 2024-07-13 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_currentbalance_current_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinghistory',
            name='current_balance',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tracker.currentbalance'),
        ),
    ]
